### PR TITLE
Add min/max temperature substitutions

### PR DESCRIPTION
**Pull request by jdwhite**
Added the ability to provide substitutions for the min_temperature and max_temperature visual component values in the local YAML configuration file. Corrected a few minor spelling and capitalization errors.

### CODE REVIEW

**Comment by barndawgie** [comment]
@jdwhite - Why do you need to override min/max? The current values are what seem to the limits of the devices' settings. Are you finding they are incorrect for your device? Or you just want to further constrain them?

**Comment by barndawgie** [comment]
@jdwhite Would you mind moving your doc fixes to a separate PR?

**Comment by jdwhite** [comment]
My device supports temps from 85-140F, and feel it's better to give the end user the ability to set their own constraints.

-Jason

**Comment by tronikos** [comment]
Can't your achieve the same with extend?

**Comment by barndawgie** [comment]
> Can't your achieve the same with extend?

I agree this is doable with !extend, but we do have other properties we are exposing via substitutions. Not sure we should go remove them as it would break compatibility, but is !extend the preferred mechanism?

**Comment by jdwhite** [comment]
This is the first ESPHome project that I've wanted to do this type of configuration change with, and I admit that this is pretty new to me. I saw existing substitutions, so what's what I went with. I wasn't aware that `!extend` was a thing or I would have tried that first. I'm not sure where the line is between "use extend" and "use substitutions".

**Comment by barndawgie** [comment]
> This is the first ESPHome project that I've wanted to do this type of configuration change with, and I admit that this is pretty new to me. I saw existing substitutions, so what's what I went with. I wasn't aware that `!extend` was a thing or I would have tried that first. I'm not sure where the line is between "use extend" and "use substitutions".

Extend is detailed here if you want to give it a try: https://esphome.io/guides/configuration-types.html#extend

For your usecase, you'd want to add something like the following to your config:
```yaml
climate:
  - id: !extend econet_climate # The ID of the climate component taht you're amending
    min_temperature: 85
    max_temperature: 140
```

**Comment by tronikos** [comment]
I'd prefer we try to avoid adding more substitutions to minimize complexity.

**Comment by barndawgie** [comment]
@jdwhite can you confirm whether that extend block works for you?

**Comment by jdwhite** [comment]
> @jdwhite can you confirm whether that extend block works for you?

I can confirm that it does, but with a slight modification to your example. I had to add the `visual:` section. Also, I have to specify my temps in Celsius. Been looking around for how to change that -- not that it matters much since it's basically a "set it and forget it", but would like to know how to modify that default.

```yaml
climate:
  - id: !extend econet_climate
    visual:
      min_temperature: "29.44" # Celsius. 29.44C ~= 85F
      max_temperature: "60"    # Celsius. 60C = 140F
```

Using `!extend` seems perfectly reasonable and sane. I have no issues with closing this request, unmerged, and I appreciate the feedback and teaching me a better way.

**Pull request closed without merging**
