### PR TITLE
Adding passive support for parsing zonestat and hwstatus

### LINKED ISSUE #221: Support parsing passive data provided by ZONESTAT for HVAC systems

### PR DESCRIPTION
**Pull request by bitfliq**
closes #221 

This also separates out any status update messages from the zone thermostats that share the same name as the main thermostat variables. (example: if data from ZONE3, will be logged to ZONE3_RELH7005 datapoint)

This update does not handle publishing variables to HA.  That will still need to happen with YAML updates.

Known issue: HWSTATUS static pressure may be incorrect.

### CODE REVIEW

**Comment by barndawgie** [comment]
Is this still relevant after #224 was checked in?

**Comment by stockmopar** [comment]
@bitfliq should we update this PR to utilize the new source address functionality?

**Comment by bitfliq** [comment]
> @bitfliq should we update this PR to utilize the new source address functionality?

That is a great idea. Please feel free if you can get to that implementation first.

**Comment by barndawgie** [comment]
I'm closing this since it hasn't been touched in a few weeks and there were substantial changes made to this area. Please feel free to re-open if you want to re-work it, or just create a new PR.

**Pull request closed without merging**
